// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class update_21130571_PhamCongToan_Lab7 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  // Hàm click kèm delay sau mỗi thao tác
  private void clickWithDelay(By locator, int delayMs) {
    driver.findElement(locator).click();
    try {
      Thread.sleep(delayMs);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
  @Test
  public void TC_PI_1() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 922));
    clickWithDelay(By.cssSelector("input"), 2000);
    {
      WebElement element = driver.findElement(By.cssSelector(".button_search"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button_search"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".button_search > svg"), 2000);
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro > span"), 2000);
  }
  @Test
  public void TC_PI_2() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 922));
    clickWithDelay(By.cssSelector("input"), 2000);
    {
      WebElement element = driver.findElement(By.cssSelector(".button_search"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button_search"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".button_search > svg"), 2000);
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro > span"), 2000);
  }
  @Test
  public void TC_PI_3() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 922));
    clickWithDelay(By.cssSelector("input"), 2000);
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro > span"), 2000);
    clickWithDelay(By.cssSelector(".dmcl-gallery > .loaded"), 2000);
    clickWithDelay(By.cssSelector("#slide_popup-img-big .owl-next"), 2000);
    clickWithDelay(By.cssSelector("#slide_popup-img-big .owl-next"), 2000);
  }
  @Test
  public void TC_PI_4() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 922));
    clickWithDelay(By.cssSelector("input"), 2000);
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.linkText("Danh mục"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro"), 2000);
    clickWithDelay(By.cssSelector(".block_item:nth-child(3) > .item"), 2000);
    clickWithDelay(By.cssSelector(".btn-closemenu"), 2000);
    clickWithDelay(By.cssSelector(".fa-info-circle"), 2000);
    clickWithDelay(By.cssSelector(".btn-closemenu"), 2000);
  }
  @Test
  public void TC_PI_5() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 928));
    clickWithDelay(By.cssSelector("input"), 2000);
    {
      WebElement element = driver.findElement(By.cssSelector(".button_search"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro > span"), 2000);
    clickWithDelay(By.cssSelector("#slide_pro .owl-next"), 2000);
    clickWithDelay(By.cssSelector(".owl-item:nth-child(3) .name_pro > .name_pro > span"), 2000);
  }
  @Test
  public void TC_PI_6() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 922));
    clickWithDelay(By.cssSelector("input"), 2000);
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro > span"), 2000);
    clickWithDelay(By.cssSelector(".rating"), 2000);
    vars.put("window_handles", driver.getWindowHandles());
    clickWithDelay(By.linkText("Xem thêm những đánh giá / hỏi đáp khác"), 2000);
    vars.put("win6455", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6455").toString());
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    js.executeScript("window.scrollTo(0,120)");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    js.executeScript("window.scrollTo(0,703)");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
  @Test
  public void TC_Cart_1() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 928));
    clickWithDelay(By.cssSelector("input"), 2000);
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro > span"), 2000);
    clickWithDelay(By.cssSelector(".click_buy"), 2000);
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".icon_trash"), 2000);
  }
  @Test
  public void TC_Cart_2() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 928));
    clickWithDelay(By.cssSelector("input"), 2000);
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro"), 2000);
    js.executeScript("window.scrollTo(0,99)");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".click_buy"), 2000);
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".icon_trash"), 2000);
  }
  @Test
  public void TC_Cart_3() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 928));
    clickWithDelay(By.cssSelector("input"), 2000);
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro > span"), 2000);
    js.executeScript("window.scrollTo(0,204)");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".click_buy"), 2000);
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("html"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".augment"), 2000);
    clickWithDelay(By.cssSelector(".abate"), 2000);
    clickWithDelay(By.cssSelector(".icon_trash"), 2000);
  }
  @Test
  public void TC_Cart_4() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 928));
    clickWithDelay(By.cssSelector("input"), 3000);
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");  // Thay query để có nhiều result
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    // Lấy list products để an toàn, click đầu tiên
    List<WebElement> products = driver.findElements(By.cssSelector(".product"));
    if (!products.isEmpty()) {
      clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro > span"), 3000);
    } else {
      System.out.println("No products found after first search");
      return;  // Thoát test nếu không có result
    }
    clickWithDelay(By.cssSelector(".click_buy > span"), 3000);
    clickWithDelay(By.cssSelector(".search_mb > input"), 3000);
    driver.findElement(By.cssSelector(".search_mb > input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");  // Thay query tương tự
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector(".search_mb > input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      WebElement element = driver.findElement(By.linkText("Bán chạy"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    // Lại lấy list products, click thứ 3 nếu tồn tại
    products = driver.findElements(By.cssSelector(".product"));
    if (products.size() >= 3) {
      products.get(2).findElement(By.cssSelector(".name_pro strong")).click();  // Sử dụng list để tránh nth-child fail
      try {
        Thread.sleep(3000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    } else {
      System.out.println("Not enough products after second search");
      return;
    }
    js.executeScript("window.scrollTo(0,72)");
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".click_buy"), 3000);
    clickWithDelay(By.cssSelector("div:nth-child(3) .remove_pro_cart > span"), 3000);
    clickWithDelay(By.cssSelector(".remove_pro_cart > span"), 3000);
  }
  @Test
  public void TC_Cart_5() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 926));
    clickWithDelay(By.cssSelector(".box_cart_new"), 2000);
    clickWithDelay(By.linkText("Mua sắm"), 2000);
  }
  @Test
  public void TC_Cart_6() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 929));
    clickWithDelay(By.cssSelector("input"), 2000);
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro > span"), 2000);
    clickWithDelay(By.cssSelector(".click_buy > span"), 2000);
    clickWithDelay(By.cssSelector(".box_cart_new"), 2000);
    clickWithDelay(By.cssSelector(".icon_trash"), 2000);
  }
  @Test
  public void TC_Cart_7() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1711, 929));
    clickWithDelay(By.cssSelector("input"), 2000);
    driver.findElement(By.cssSelector("input")).sendKeys("Tủ Lạnh Hitachi Inverter 339 Lít R-FVX450PGV9 GBK");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".product:nth-child(1) .name_pro > .name_pro > span"), 2000);
    js.executeScript("window.scrollTo(0,303)");
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    clickWithDelay(By.cssSelector(".click_buy"), 2000);
    clickWithDelay(By.linkText("Quay lại mua thêm sản phẩm khác"), 2000);
    clickWithDelay(By.cssSelector(".box_cart_new"), 2000);
    clickWithDelay(By.cssSelector(".remove_pro_cart > span"), 2000);
  }
}