// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Module2UDSPSuitTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCUD1() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box .icon_login")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("098phamtrung@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("dienmay1106%");
    driver.findElement(By.cssSelector(".btn_register > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box > a:nth-child(1) > span")).click();
    driver.findElement(By.linkText("Sửa")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("098phamtrungze@gmail.com");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.elementToBeClickable(By.name("email")));
    }
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("098phamtrung@gmail.com");
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".logout > span")).click();
  }
  @Test
  public void tCUD2() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1536, 824));
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box .icon_login")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("098phamtrung@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("dienmay1106%");
    driver.findElement(By.cssSelector(".btn_register")).click();
    driver.findElement(By.cssSelector("#user_box > a:nth-child(1) > span")).click();
    driver.findElement(By.linkText("Sửa")).click();
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).sendKeys("0886373383");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).sendKeys("0886373384");
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".logout > span")).click();
  }
  @Test
  public void tCUD3() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box .icon_login")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("098phamtrung@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("dienmay1106%");
    driver.findElement(By.cssSelector(".btn_register > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box > a:nth-child(1) > span")).click();
    driver.findElement(By.linkText("Sửa")).click();
    driver.findElement(By.name("fullname")).click();
    driver.findElement(By.name("fullname")).sendKeys("Pham Trung T");
    driver.findElement(By.id("day")).click();
    {
      WebElement dropdown = driver.findElement(By.id("day"));
      dropdown.findElement(By.xpath("//option[. = '12']")).click();
    }
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys("174/33, Khu Phố 3, Phường Trung Dũng, TP.Biên Hoà A");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys("174/33, Khu Phố 3, Phường Trung Dũng, TP.Biên Hoà");
    driver.findElement(By.id("day")).click();
    {
      WebElement dropdown = driver.findElement(By.id("day"));
      dropdown.findElement(By.xpath("//option[. = '11']")).click();
    }
    driver.findElement(By.name("fullname")).click();
    driver.findElement(By.name("fullname")).sendKeys("Pham Trung");
    driver.findElement(By.id("f_info")).click();
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".logout > span")).click();
  }
  @Test
  public void tCSP1() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("input")).click();
    driver.findElement(By.cssSelector("input")).sendKeys("Iphone");
    driver.findElement(By.cssSelector(".button_search > svg")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".product:nth-child(1) .img_pro")));
    }
    vars.put("result", js.executeScript("var items = document.querySelectorAll(\'.product .name_pro\');  var hasIphone = false;   items.forEach(i => {          let t = i.innerText.toLowerCase().trim();          if (t.includes(\'iphone\')) hasIphone = true;  });    return hasIphone ? true : false;"));
    assertEquals(vars.get("result").toString(), "true");
  }
  @Test
  public void tCSP2() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("input")).click();
    driver.findElement(By.cssSelector("input")).sendKeys("laptop");
    driver.findElement(By.cssSelector(".button_search > svg")).click();
    vars.put("count", js.executeScript("var items = document.querySelectorAll(\'.product .name_pro\'); return items.length === 0 ? true : false;"));
    assertEquals(vars.get("count").toString(), "true");
  }
  @Test
  public void tCSP3() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("input")).click();
    driver.findElement(By.cssSelector("input")).sendKeys("!@###$@^^$@#$$#%^");
    driver.findElement(By.cssSelector(".button_search > svg")).click();
    vars.put("count", js.executeScript("var items = document.querySelectorAll(\'.product .name_pro\'); return items.length === 0 ? true : false;"));
    assertEquals(vars.get("count").toString(), "true");
  }
}
