package org.example.testSuite;// Generated by Selenium IDE
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class LeThanhTam_lab7_21130526 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    WebDriverWait wait;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        js = (JavascriptExecutor) driver;
        driver.manage().window().maximize();
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    private void login() {
        driver.get("https://dienmaycholon.com/dang-nhap");

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("username")))
                .sendKeys("LeTana");

        driver.findElement(By.id("password")).sendKeys("Tam123@");

        driver.findElement(By.cssSelector(".btn_register > span")).click();

        // Chờ login xong
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Địa chỉ của bạn")));
    }

    @Test
    public void test01_CorrectInformation() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("THÊM ĐỊA CHỈ MỚI"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("Lê Quang Dũng");
        driver.findElement(By.name("phone")).sendKeys("0912312312");
        driver.findElement(By.name("address")).sendKeys("06 Lê Thánh Tông");

        // Chọn tỉnh
//        {
//            WebElement dropdown = driver.findElement(By.id("cid_city"));
//            dropdown.findElement(By.xpath("//option[. = 'Đắk Lắk']")).click();
//        }
        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();

//        driver.findElement(By.cssSelector("button[type='submit']")).click();

        // Kiểm tra quay lại trang danh sách
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("QUẢN LÝ TÀI KHOẢN")));
    }
    @Test
    public void test02_ChooseDefault() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("THÊM ĐỊA CHỈ MỚI"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("Lê Quang Dũng");
        driver.findElement(By.name("phone")).sendKeys("0912312312");
        driver.findElement(By.name("address")).sendKeys("06 Lê Thánh Tông");

        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.name("is_default")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test03_NameNull() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("THÊM ĐỊA CHỈ MỚI"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("");
        driver.findElement(By.name("phone")).sendKeys("0912312312");
        driver.findElement(By.name("address")).sendKeys("06 Lê Thánh Tông");

        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.name("is_default")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test04_NameNumberOnly() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("THÊM ĐỊA CHỈ MỚI"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("0911111111111111");
        driver.findElement(By.name("phone")).sendKeys("0912312312");
        driver.findElement(By.name("address")).sendKeys("06 Lê Thánh Tông");

        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.name("is_default")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test05_NameTooLong() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("THÊM ĐỊA CHỈ MỚI"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("hạkashfjkdshfkjhsdjfhjkdsfkjsdhkjfhsdjfjksdhfkjshdjkfhsdjhfkjdshjfkhsdjfhjkdsfjk");
        driver.findElement(By.name("phone")).sendKeys("0912312312");
        driver.findElement(By.name("address")).sendKeys("06 Lê Thánh Tông");

        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.name("is_default")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test06_PhoneNull() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        WebElement deleteBtn = wait.until(
                ExpectedConditions.elementToBeClickable(By.cssSelector(".delete"))
        );
        deleteBtn.click();
        assertThat(driver.switchTo().alert().getText(), is("Bạn muốn xoá địa chỉ này"));
        driver.switchTo().alert().accept();
        WebElement addBtn = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.linkText("THÊM ĐỊA CHỈ MỚI"))
        );
        ((JavascriptExecutor) driver).executeScript(
                "arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", addBtn
        );
        wait.until(ExpectedConditions.elementToBeClickable(addBtn));

        ((JavascriptExecutor) driver).executeScript("arguments[0].click();", addBtn);


        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("Lê Tuấn Dũng");
        driver.findElement(By.name("phone")).sendKeys("");
        driver.findElement(By.name("address")).sendKeys("06 Lê Thánh Tông");

        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.name("is_default")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test07_PhoneShort() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("THÊM ĐỊA CHỈ MỚI"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("Lê Tuấn Dũng");
        driver.findElement(By.name("phone")).sendKeys("09343");
        driver.findElement(By.name("address")).sendKeys("06 Lê Thánh Tông");

        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.name("is_default")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test08_PhoneContainsWords() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("THÊM ĐỊA CHỈ MỚI"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("Lê Tuấn Dũng");
        driver.findElement(By.name("phone")).sendKeys("a87ddd#ghàha");
        driver.findElement(By.name("address")).sendKeys("06 Lê Thánh Tông");

        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.name("is_default")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test09_PhoneTooLong() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        WebElement deleteBtn = wait.until(
                ExpectedConditions.elementToBeClickable(By.cssSelector(".delete"))
        );
        deleteBtn.click();
        assertThat(driver.switchTo().alert().getText(), is("Bạn muốn xoá địa chỉ này"));
        driver.switchTo().alert().accept();
        WebElement addBtn = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.linkText("THÊM ĐỊA CHỈ MỚI"))
        );
        ((JavascriptExecutor) driver).executeScript(
                "arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", addBtn
        );
        wait.until(ExpectedConditions.elementToBeClickable(addBtn));

        ((JavascriptExecutor) driver).executeScript("arguments[0].click();", addBtn);


        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("Lê Tuấn Dũng");
        driver.findElement(By.name("phone")).sendKeys("9089034878357257238");
        driver.findElement(By.name("address")).sendKeys("06 Lê Thánh Tông");

        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.name("is_default")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test10_NoCity() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("THÊM ĐỊA CHỈ MỚI"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("Lê Tuấn Dũng");
        driver.findElement(By.name("phone")).sendKeys("a87ddd#ghàha");
        driver.findElement(By.name("address")).sendKeys("06 Lê Thánh Tông");

        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test11_AddressInvalid() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("THÊM ĐỊA CHỈ MỚI"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("Lê Tuấn Dũng");
        driver.findElement(By.name("phone")).sendKeys("a87ddd#ghàha");
        driver.findElement(By.name("address")).sendKeys("a87ddd#ghàha");

        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.name("is_default")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test12_AddressNull() {
        login();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Địa chỉ của bạn"))).click();
        wait.until(ExpectedConditions.elementToBeClickable(By.linkText("THÊM ĐỊA CHỈ MỚI"))).click();

        wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("name")))
                .sendKeys("Lê Tuấn Dũng");
        driver.findElement(By.name("phone")).sendKeys("a87ddd#ghàha");
        driver.findElement(By.name("address")).sendKeys("");

        {
            WebElement citySelect = driver.findElement(By.id("cid_city"));
            Select select = new Select(citySelect);
            select.selectByVisibleText("Đồng Tháp");
        }
        driver.findElement(By.name("is_default")).click();
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    }
    @Test
    public void test13FPInvalidateEmail() {
        // Test name: TC13_FP_InvalidateEmail
        // Step # | name | target | value | comment
        // 1 | open | https://dienmaycholon.com/thong-tin-tai-khoan |  |
        driver.get("https://dienmaycholon.com/thong-tin-tai-khoan");
        // 2 | setWindowSize | 1186x797 |  |
        driver.manage().window().setSize(new Dimension(1186, 797));
        // 3 | click | css=.logout > span |  |
        driver.findElement(By.cssSelector(".logout > span")).click();
        // 4 | type | name=username | LeTana |
        driver.findElement(By.name("username")).sendKeys("LeTana");
        // 5 | type | id=password | Tam123@ |
        driver.findElement(By.id("password")).sendKeys("Tam123@");
        // 6 | click | linkText=Bạn quên mật khẩu? |  |
        driver.findElement(By.linkText("Bạn quên mật khẩu?")).click();
        // 7 | click | id=user |  |
        driver.findElement(By.id("user")).click();
        // 8 | type | id=user | ya@hhsdfa |
        driver.findElement(By.id("user")).sendKeys("ya@hhsdfa");
        // 9 | click | css=.btn_register |  |
        driver.findElement(By.cssSelector(".btn_register")).click();
    }
    @Test
    public void test14FPWrongEmail() {
        // Test name: TC14_FP_WrongEmail
        // Step # | name | target | value | comment
        // 1 | open | https://dienmaycholon.com/dang-nhap |  |
        driver.get("https://dienmaycholon.com/dang-nhap");
        // 2 | setWindowSize | 1187x798 |  |
        driver.manage().window().setSize(new Dimension(1187, 798));
        // 3 | type | name=username | LeTana |
        driver.findElement(By.name("username")).sendKeys("LeTana");
        // 4 | type | id=password | Tam123@ |
        driver.findElement(By.id("password")).sendKeys("Tam123@");
        // 5 | click | linkText=Bạn quên mật khẩu? |  |
        driver.findElement(By.linkText("Bạn quên mật khẩu?")).click();
        // 6 | click | id=user |  |
        driver.findElement(By.id("user")).click();
        // 7 | type | id=user | ya@hhsdfa |
        driver.findElement(By.id("user")).sendKeys("ya@hhsdfa");
        // 8 | type | id=user | ya@hhsdfa@gmail.com |
        driver.findElement(By.id("user")).sendKeys("ya@hhsdfa@gmail.com");
        // 9 | click | css=.btn_register > span |  |
        driver.findElement(By.cssSelector(".btn_register > span")).click();
        // 10 | click | id=user |  |
        driver.findElement(By.id("user")).click();
        // 11 | type | id=user | ya@gmail.com |
        driver.findElement(By.id("user")).sendKeys("ya@gmail.com");
        // 12 | click | css=.btn_register |  |
        driver.findElement(By.cssSelector(".btn_register")).click();
        // 13 | click | linkText=Trở lại đăng nhập |  |
        driver.findElement(By.linkText("Trở lại đăng nhập")).click();
    }
    @Test
    public void test15FPCorrectEmail() {
        // Test name: TC15_FP_CorrectEmail
        // Step # | name | target | value | comment
        // 1 | open | https://dienmaycholon.com/dang-nhap |  |
        driver.get("https://dienmaycholon.com/dang-nhap");
        // 2 | setWindowSize | 1188x799 |  |
        driver.manage().window().setSize(new Dimension(1188, 799));
        // 3 | type | name=username | LeTana |
        driver.findElement(By.name("username")).sendKeys("LeTana");
        // 4 | type | id=password | Tam123@ |
        driver.findElement(By.id("password")).sendKeys("Tam123@");
        // 5 | click | linkText=Bạn quên mật khẩu? |  |
        driver.findElement(By.linkText("Bạn quên mật khẩu?")).click();
        // 6 | click | id=user |  |
        driver.findElement(By.id("user")).click();
        // 7 | type | id=user | tamle7723@gmail.com |
        driver.findElement(By.id("user")).sendKeys("tamle7723@gmail.com");
        // 8 | click | css=.btn_register |  |
        driver.findElement(By.cssSelector(".btn_register")).click();
        // 9 | click | linkText=Trở lại đăng nhập |  |
        driver.findElement(By.linkText("Trở lại đăng nhập")).click();
    }
}

