// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;

public class PhamPhiTruong_21130593_Lab8 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCUD1() throws InterruptedException {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box .icon_login")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("098phamtrung@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("dienmay1106%");
    driver.findElement(By.cssSelector(".btn_register > span")).click();
    Thread.sleep(3000);
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box > a:nth-child(1) > span")).click();
    driver.findElement(By.linkText("Sửa")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).clear();
    driver.findElement(By.name("email")).sendKeys("098phamtrungze@gmail.com");
    driver.findElement(By.cssSelector("button[type='submit']")).click();
    Thread.sleep(3000);
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
      wait.until(ExpectedConditions.elementToBeClickable(By.name("email")));
    }
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).clear();
    driver.findElement(By.name("email")).sendKeys("098phamtrung@gmail.com");
    driver.findElement(By.cssSelector("button[type='submit']")).click();
    Thread.sleep(3000);
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".logout > span")).click();
  }
  @Test
  public void tCUD2() throws InterruptedException {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1536, 824));
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box .icon_login")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("098phamtrung@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("dienmay1106%");
    driver.findElement(By.cssSelector(".btn_register")).click();
    Thread.sleep(3000);
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box > a:nth-child(1) > span")).click();
    driver.findElement(By.linkText("Sửa")).click();
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).clear();
    driver.findElement(By.name("phone")).sendKeys("0886373383");
    driver.findElement(By.cssSelector("button[type='submit']")).click();
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).clear();
    driver.findElement(By.name("phone")).sendKeys("0886373384");
    driver.findElement(By.cssSelector("button[type='submit']")).click();
    Thread.sleep(3000);
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".logout > span")).click();
  }
  @Test
  public void tCUD3() throws InterruptedException {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box .icon_login")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("098phamtrung@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("dienmay1106%");
    driver.findElement(By.cssSelector(".btn_register > span")).click();
    Thread.sleep(3000);
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#user_box > a:nth-child(1) > span")).click();
    driver.findElement(By.linkText("Sửa")).click();
    driver.findElement(By.name("fullname")).click();
    driver.findElement(By.name("fullname")).clear();
    driver.findElement(By.name("fullname")).sendKeys("Pham Trung T");
    driver.findElement(By.id("day")).click();
    Thread.sleep(2000);
    {
      WebElement dropdown = driver.findElement(By.id("day"));
      Select selectDay = new Select(dropdown);
      selectDay.selectByVisibleText("12");
    }
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).clear();
    driver.findElement(By.name("address")).sendKeys("174/33, Khu Phố 3, Phường Trung Dũng, TP.Biên Hoà A");
    driver.findElement(By.cssSelector("button[type='submit']")).click();
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).clear();
    driver.findElement(By.name("address")).sendKeys("174/33, Khu Phố 3, Phường Trung Dũng, TP.Biên Hoà");
    driver.findElement(By.id("day")).click();
    Thread.sleep(2000);
    {
      WebElement dropdown = driver.findElement(By.id("day"));
      Select selectDay = new Select(dropdown);
      selectDay.selectByVisibleText("11");
    }
    driver.findElement(By.name("fullname")).click();
    driver.findElement(By.name("fullname")).clear();
    driver.findElement(By.name("fullname")).sendKeys("Pham Trung");
    driver.findElement(By.id("f_info")).click();
    driver.findElement(By.cssSelector("button[type='submit']")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".box_account > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".logout > span")).click();
  }
  @Test
  public void tCSP1() throws InterruptedException {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("input")).click();
    driver.findElement(By.cssSelector("input")).sendKeys("Iphone");
    driver.findElement(By.cssSelector(".button_search > svg")).click();
    Thread.sleep(3000);
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".product:nth-child(1) .img_pro")));
    }
    vars.put("result", js.executeScript("var items = document.querySelectorAll(\'.product .name_pro\');  var hasIphone = false;   items.forEach(i => {          let t = i.innerText.toLowerCase().trim();          if (t.includes(\'iphone\')) hasIphone = true;  });    return hasIphone ? true : false;"));
    assertEquals(vars.get("result").toString(), "true");
  }
  @Test
  public void tCSP2() throws InterruptedException {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("input")).click();
    driver.findElement(By.cssSelector("input")).sendKeys("laptop");
    driver.findElement(By.cssSelector(".button_search > svg")).click();
    Thread.sleep(3000);
    vars.put("count", js.executeScript("var items = document.querySelectorAll(\'.product .name_pro\'); return items.length === 0 ? true : false;"));
    assertEquals(vars.get("count").toString(), "true");
  }
  @Test
  public void tCSP3() throws InterruptedException {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector("input")).click();
    driver.findElement(By.cssSelector("input")).sendKeys("!@###$@^^$@#$$#%^");
    driver.findElement(By.cssSelector(".button_search > svg")).click();
    Thread.sleep(3000);
    vars.put("count", js.executeScript("var items = document.querySelectorAll(\'.product .name_pro\'); return items.length === 0 ? true : false;"));
    assertEquals(vars.get("count").toString(), "true");
  }
}
