// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class PhamHoangTien_21130562_Lab8 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCCP1() {
    driver.get("https://dienmaycholon.com/dang-nhap");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("phamhoangtien832003@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("12345678");
    driver.findElement(By.cssSelector(".btn_register")).click();
    driver.findElement(By.linkText("Đổi mật khẩu")).click();
    driver.findElement(By.name("oldpassword")).click();
    driver.findElement(By.name("oldpassword")).sendKeys("12345678");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("12345678");
    driver.findElement(By.name("repassword")).click();
    driver.findElement(By.name("repassword")).sendKeys("12345678");
    driver.findElement(By.cssSelector(".btn_confirm")).click();
  }
  @Test
  public void tCCP2() {
    driver.get("https://dienmaycholon.com/thong-tin-tai-khoan");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.linkText("Đổi mật khẩu")).click();
    driver.findElement(By.name("oldpassword")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("12345678");
    driver.findElement(By.name("repassword")).click();
    driver.findElement(By.name("repassword")).sendKeys("12345678");
    driver.findElement(By.cssSelector(".btn_confirm")).click();
  }
  @Test
  public void tCCP3() {
    driver.get("https://dienmaycholon.com/thong-tin-tai-khoan");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.linkText("Đổi mật khẩu")).click();
    driver.findElement(By.name("oldpassword")).click();
    driver.findElement(By.name("oldpassword")).sendKeys("123456");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("12345678");
    driver.findElement(By.name("repassword")).click();
    driver.findElement(By.name("repassword")).sendKeys("12345678");
    driver.findElement(By.id("f_password")).click();
    driver.findElement(By.cssSelector(".btn_confirm")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn_confirm"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
  @Test
  public void tCCP4() {
    driver.get("https://dienmaycholon.com/thong-tin-tai-khoan");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.linkText("Đổi mật khẩu")).click();
    driver.findElement(By.name("oldpassword")).click();
    driver.findElement(By.name("oldpassword")).sendKeys("12345678");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123456");
    driver.findElement(By.name("repassword")).click();
    driver.findElement(By.name("repassword")).sendKeys("1234567");
    driver.findElement(By.cssSelector(".btn_confirm")).click();
  }
  @Test
  public void tCCP5() {
    driver.get("https://dienmaycholon.com/thong-tin-tai-khoan");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.linkText("Đổi mật khẩu")).click();
    driver.findElement(By.name("oldpassword")).click();
    driver.findElement(By.name("oldpassword")).sendKeys("12345678");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123");
    driver.findElement(By.name("repassword")).click();
    driver.findElement(By.name("repassword")).sendKeys("123");
    driver.findElement(By.cssSelector(".btn_confirm")).click();
  }
  @Test
  public void tCFilter1() {
    driver.get("https://dienmaycholon.com/tu-khoa/tivi");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.cssSelector(".filter-total > .filter-item__title")).click();
    driver.findElement(By.linkText("Từ 5 - 7 triệu")).click();
    driver.findElement(By.cssSelector(".filter-button--total > .btn-filter-readmore")).click();
  }
  @Test
  public void tCFilter2() {
    driver.get("https://dienmaycholon.com/tu-khoa/tivi");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.cssSelector(".filter-total > .filter-item__title")).click();
    {
      WebElement element = driver.findElement(By.id("wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("elm_start")).click();
    driver.findElement(By.id("elm_start")).sendKeys("5");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("5");
    driver.findElement(By.id("elm_start")).sendKeys("50");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("50");
    driver.findElement(By.id("elm_start")).sendKeys("500");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("500");
    driver.findElement(By.id("elm_start")).sendKeys("5.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("5.000");
    driver.findElement(By.id("elm_start")).sendKeys("50.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("50.000");
    driver.findElement(By.id("elm_start")).sendKeys("500.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("500.000");
    driver.findElement(By.id("elm_start")).sendKeys("5.000.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("5.000.000");
    driver.findElement(By.id("elm_end")).sendKeys("1");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("1");
    driver.findElement(By.id("elm_end")).sendKeys("10");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("10");
    driver.findElement(By.id("elm_end")).sendKeys("100");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("100");
    driver.findElement(By.id("elm_end")).sendKeys("1.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("1.000");
    driver.findElement(By.id("elm_end")).sendKeys("10.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("10.000");
    driver.findElement(By.id("elm_end")).sendKeys("100.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("100.000");
    driver.findElement(By.id("elm_end")).sendKeys("1.000.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("1.000.000");
    driver.findElement(By.id("elm_end")).sendKeys("10.000.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("10.000.000");
    driver.findElement(By.linkText("Tìm theo giá mong muốn")).click();
    {
      WebElement element = driver.findElement(By.linkText("Tìm theo giá mong muốn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".filter-button--total > .btn-filter-readmore")).click();
  }
  @Test
  public void tCFilter3() {
    driver.get("https://dienmaycholon.com/tu-khoa/tivi");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.cssSelector(".filter-total > .filter-item__title")).click();
    driver.findElement(By.id("elm_start")).click();
    driver.findElement(By.id("elm_start")).sendKeys("1");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("1");
    driver.findElement(By.id("elm_start")).sendKeys("15");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("15");
    driver.findElement(By.id("elm_start")).sendKeys("150");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("150");
    driver.findElement(By.id("elm_start")).sendKeys("1.500");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("1.500");
    driver.findElement(By.id("elm_start")).sendKeys("15.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("15.000");
    driver.findElement(By.id("elm_start")).sendKeys("150.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("150.000");
    driver.findElement(By.id("elm_start")).sendKeys("1.500.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("1.500.000");
    driver.findElement(By.id("elm_start")).sendKeys("15.000.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_start")).sendKeys("15.000.000");
    driver.findElement(By.id("elm_end")).sendKeys("1");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("1");
    driver.findElement(By.id("elm_end")).sendKeys("10");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("10");
    driver.findElement(By.id("elm_end")).sendKeys("100");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("100");
    driver.findElement(By.id("elm_end")).sendKeys("1.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("1.000");
    driver.findElement(By.id("elm_end")).sendKeys("10.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("10.000");
    driver.findElement(By.id("elm_end")).sendKeys("100.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("100.000");
    driver.findElement(By.id("elm_end")).sendKeys("1.000.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("1.000.000");
    driver.findElement(By.id("elm_end")).sendKeys("10.000.000");
    driver.findElement(By.cssSelector(".show-total-item:nth-child(10) #elm_end")).sendKeys("10.000.000");
    driver.findElement(By.linkText("Tìm theo giá mong muốn")).click();
  }
  @Test
  public void tCFilter4() {
    driver.get("https://dienmaycholon.com/tu-khoa/tivi");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.cssSelector(".filter-total > .filter-item__title")).click();
    driver.findElement(By.cssSelector(".filter-list:nth-child(2) > .c-btnbox:nth-child(2) > img")).click();
    driver.findElement(By.cssSelector(".filter-button--total > .btn-filter-readmore")).click();
  }
  @Test
  public void tCFilter5() {
    driver.get("https://dienmaycholon.com/tu-khoa/tivi");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.cssSelector(".filter-total > .filter-item__title")).click();
    driver.findElement(By.cssSelector(".filter-list:nth-child(2) > .filter-logo:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".filter-list:nth-child(2) > .filter-logo:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".filter-button--total > .btn-filter-readmore")).click();
  }
  @Test
  public void tCFilter6() {
    driver.get("https://dienmaycholon.com/tu-khoa/tivi");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.cssSelector(".filter-total > .filter-item__title")).click();
    driver.findElement(By.linkText("Từ 5 - 7 triệu")).click();
    driver.findElement(By.cssSelector(".filter-list:nth-child(2) > .filter-logo:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".filter-button--total > .btn-filter-readmore")).click();
  }
  @Test
  public void tCFilter7() {
    driver.get("https://dienmaycholon.com/tu-khoa/tivi");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.cssSelector(".filter-total > .filter-item__title")).click();
    driver.findElement(By.cssSelector(".filter-list:nth-child(2) > .c-btnbox:nth-child(2) > img")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".filter-list:nth-child(2) > .c-btnbox:nth-child(2) > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Từ 5 - 7 triệu")).click();
    driver.findElement(By.cssSelector(".clr-filter > span")).click();
    driver.findElement(By.cssSelector(".filter-button--total > .btn-filter-readmore")).click();
  }
}
