// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class TestPhamHoangTien_21130562_Lab8 {
 private WebDriver driver;
 private Map<String, Object> vars;
 JavascriptExecutor js;
 @Before
 public void setUp() {
  driver = new ChromeDriver();
  js = (JavascriptExecutor) driver;
  vars = new HashMap<String, Object>();
 }
 @After
 public void tearDown() {
  driver.quit();
 }
 @Test
 public void tCCP1() {
  driver.get("https://dienmaycholon.com/dang-nhap");
  driver.manage().window().setSize(new Dimension(1296, 688));
  driver.findElement(By.name("username")).click();
  driver.findElement(By.name("username")).sendKeys("phamhoangtien832003@gmail.com");
  driver.findElement(By.id("password")).click();
  driver.findElement(By.id("password")).sendKeys("12345678");
  driver.findElement(By.cssSelector(".btn_register")).click();
  driver.findElement(By.linkText("Đổi mật khẩu")).click();
  driver.findElement(By.name("oldpassword")).click();
  driver.findElement(By.name("oldpassword")).sendKeys("12345678");
  driver.findElement(By.name("password")).click();
  driver.findElement(By.name("password")).sendKeys("12345678");
  driver.findElement(By.name("repassword")).click();
  driver.findElement(By.name("repassword")).sendKeys("12345678");
  driver.findElement(By.cssSelector(".btn_confirm")).click();
 }
 @Test
 public void tCCP2() {
  driver.get("https://dienmaycholon.com/dang-nhap");
  driver.manage().window().setSize(new Dimension(1296, 688));
  driver.findElement(By.name("username")).click();
  driver.findElement(By.name("username")).sendKeys("phamhoangtien832003@gmail.com");
  driver.findElement(By.id("password")).click();
  driver.findElement(By.id("password")).sendKeys("12345678");
  driver.findElement(By.cssSelector(".btn_register")).click();
  driver.findElement(By.linkText("Đổi mật khẩu")).click();
  driver.findElement(By.name("oldpassword")).click();
  driver.findElement(By.name("oldpassword")).sendKeys("123456");
  driver.findElement(By.name("password")).click();
  driver.findElement(By.name("password")).sendKeys("12345678");
  driver.findElement(By.name("repassword")).click();
  driver.findElement(By.name("repassword")).sendKeys("12345678");
  driver.findElement(By.id("f_password")).click();
  driver.findElement(By.cssSelector(".btn_confirm")).click();
  {
   WebElement element = driver.findElement(By.cssSelector(".btn_confirm"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
  }
 }
 @Test
 public void tCCP3() {
  driver.get("https://dienmaycholon.com/dang-nhap");
  driver.manage().window().setSize(new Dimension(1296, 688));
  driver.findElement(By.name("username")).click();
  driver.findElement(By.name("username")).sendKeys("phamhoangtien832003@gmail.com");
  driver.findElement(By.id("password")).click();
  driver.findElement(By.id("password")).sendKeys("12345678");
  driver.findElement(By.cssSelector(".btn_register")).click();
  driver.findElement(By.linkText("Đổi mật khẩu")).click();
  driver.findElement(By.name("oldpassword")).click();
  driver.findElement(By.name("oldpassword")).sendKeys("12345678");
  driver.findElement(By.name("password")).click();
  driver.findElement(By.name("password")).sendKeys("123456");
  driver.findElement(By.name("repassword")).click();
  driver.findElement(By.name("repassword")).sendKeys("1234567");
  driver.findElement(By.cssSelector(".btn_confirm")).click();
 }
 @Test
 public void tCCP4() {
  driver.get("https://dienmaycholon.com/dang-nhap");
  driver.manage().window().setSize(new Dimension(1296, 688));
  driver.findElement(By.name("username")).click();
  driver.findElement(By.name("username")).sendKeys("phamhoangtien832003@gmail.com");
  driver.findElement(By.id("password")).click();
  driver.findElement(By.id("password")).sendKeys("12345678");
  driver.findElement(By.cssSelector(".btn_register")).click();
  driver.findElement(By.linkText("Đổi mật khẩu")).click();
  driver.findElement(By.name("oldpassword")).click();
  driver.findElement(By.name("oldpassword")).sendKeys("12345678");
  driver.findElement(By.name("password")).click();
  driver.findElement(By.name("password")).sendKeys("123");
  driver.findElement(By.name("repassword")).click();
  driver.findElement(By.name("repassword")).sendKeys("123");
  driver.findElement(By.cssSelector(".btn_confirm")).click();
 }
 @Test
 public void tCFilter1() {
  driver.get("https://dienmaycholon.com/tu-khoa/tivi");
  driver.manage().window().setSize(new Dimension(1296, 688));
  driver.findElement(By.cssSelector(".filter-total > .filter-item__title")).click();
  driver.findElement(By.linkText("Từ 5 - 7 triệu")).click();
  driver.findElement(By.cssSelector(".filter-button--total > .btn-filter-readmore")).click();
 }
 @Test
 public void tCFilter2() {
  driver.get("https://dienmaycholon.com/tu-khoa/tivi");
  driver.manage().window().setSize(new Dimension(1296, 688));
  driver.findElement(By.cssSelector(".filter-total > .filter-item__title")).click();
  driver.findElement(By.cssSelector(".filter-list:nth-child(2) > .c-btnbox:nth-child(2) > img")).click();
  driver.findElement(By.cssSelector(".filter-button--total > .btn-filter-readmore")).click();
 }
 @Test
 public void tCFilter3() {
  driver.get("https://dienmaycholon.com/tu-khoa/tivi");
  driver.manage().window().setSize(new Dimension(1296, 688));
  driver.findElement(By.cssSelector(".filter-total > .filter-item__title")).click();
  driver.findElement(By.cssSelector(".filter-list:nth-child(2) > .filter-logo:nth-child(2)")).click();
  driver.findElement(By.cssSelector(".filter-list:nth-child(2) > .filter-logo:nth-child(3)")).click();
  driver.findElement(By.cssSelector(".filter-button--total > .btn-filter-readmore")).click();
 }
}