// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class TestNguyenThaiToan_21130569_Lab8 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void tCFS1() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Chi nhánh")).click();
    vars.put("win3725", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3725").toString());
    driver.findElement(By.cssSelector(".select2-container--below .select2-selection")).click();
    driver.findElement(By.cssSelector(".select2-search__field")).sendKeys("an");
    driver.findElement(By.cssSelector(".select2-search__field")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".button_branch")).click();
  }
  @Test
  public void tCFS2() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Chi nhánh")).click();
    vars.put("win4578", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win4578").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().window(vars.get("win4578").toString());
    driver.findElement(By.cssSelector(".select2-container--below .select2-selection")).click();
    driver.findElement(By.cssSelector(".select2-search__field")).sendKeys("b");
    driver.findElement(By.cssSelector(".select2-search__field")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".select2-container--open .select2-selection")).click();
    driver.findElement(By.cssSelector(".select2-search__field")).sendKeys("v");
    driver.findElement(By.cssSelector(".select2-search__field")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".button_branch")).click();
  }
  @Test
  public void tCFS3() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.cssSelector(".boxbranch")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Chi nhánh")).click();
    vars.put("win5273", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5273").toString());
    driver.findElement(By.cssSelector(".container_cart:nth-child(1) > a")).click();
  }
  @Test
  public void tCCQA1() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.cssSelector(".owl-item:nth-child(1) > .product_main_so_suat > .product:nth-child(1) .img_pro > .lazy")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Viết đánh giá / hỏi đáp ngay")).click();
    vars.put("win5951", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5951").toString());
    js.executeScript("window.scrollTo(0,38)");
    js.executeScript("window.scrollTo(0,2200)");
    driver.findElement(By.cssSelector("#form_cmt0 textarea")).click();
    driver.findElement(By.cssSelector("#form_cmt0 textarea")).sendKeys("test");
    driver.findElement(By.cssSelector("#form_cmt0 textarea")).click();
    driver.findElement(By.cssSelector("#form_cmt0 textarea")).sendKeys("còn hàng không ạ?");
    driver.findElement(By.cssSelector("#form_cmt0 .btn_name > .infoname")).click();
    driver.findElement(By.cssSelector("#form_cmt0 .btn_name > .infoname")).click();
    driver.findElement(By.cssSelector("#form_cmt0 .btn_name > .infoname")).sendKeys("test");
    driver.findElement(By.cssSelector("#form_cmt0 > .sent")).click();
  }
  @Test
  public void tCCQA2() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.cssSelector("input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".button_search > svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("input")).sendKeys("Smart Tivi");
    driver.findElement(By.cssSelector(".button_search > svg")).click();
    driver.findElement(By.cssSelector(".products > .product:nth-child(1) .img_pro > .lazy")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Viết đánh giá / hỏi đáp ngay")).click();
    vars.put("win8648", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8648").toString());
    js.executeScript("window.scrollTo(0,2200)");
    driver.findElement(By.cssSelector("#form_cmt0 textarea")).click();
    driver.findElement(By.cssSelector("#form_cmt0 textarea")).sendKeys("Còn hàng không?");
    driver.findElement(By.cssSelector("#form_cmt0 > .sent")).click();
  }
  @Test
  public void tCCQA3() {
    driver.get("https://dienmaycholon.com/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.cssSelector("input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".button_search > svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("input")).sendKeys("Smart Tivi");
    driver.findElement(By.cssSelector(".button_search > svg")).click();
    driver.findElement(By.cssSelector(".products > .product:nth-child(1) .img_pro")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Viết đánh giá / hỏi đáp ngay")).click();
    vars.put("win709", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win709").toString());
    js.executeScript("window.scrollTo(0,2400)");
    driver.findElement(By.cssSelector("#form_cmt0 textarea")).click();
    driver.findElement(By.cssSelector("#form_cmt0 textarea")).sendKeys("Còn hàng không?");
    driver.findElement(By.cssSelector("#form_cmt0 .btn_name > .infoname")).click();
    driver.findElement(By.cssSelector("#form_cmt0 .btn_name > .infoname")).sendKeys("test");
    driver.findElement(By.cssSelector("#form_cmt0 .btn_email > .infoname")).click();
    driver.findElement(By.cssSelector(".border-top-0:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#form_cmt0 > .sent")).click();
  }
}
